#!/usr/bin/env python3
"""Generate CMake bindings for the standalone filter-chain manifest."""

import argparse
import json
import pathlib
import sys


def die(message: str) -> None:
    print(f"[manifest-info] {message}", file=sys.stderr)
    sys.exit(1)


def collect_entries(manifest: dict, key: str, repo_root: pathlib.Path) -> list[str]:
    raw = manifest.get(key)
    if not isinstance(raw, list) or not raw:
        die(f"manifest missing '{key}' entries")
    entries: list[str] = []
    for entry in raw:
        if not isinstance(entry, str):
            die(f"manifest '{key}' entries must be strings")
        rel_path = pathlib.Path(entry)
        if rel_path.is_absolute() or ".." in rel_path.parts:
            die(f"manifest '{key}' entry '{entry}' must be repository-relative")
        full_path = (repo_root / rel_path).resolve()
        if not full_path.exists():
            die(f"manifest '{key}' target missing: {full_path}")
        entries.append(str(full_path))
    return entries


def write_list(f: pathlib.Path, var_name: str, values: list[str]) -> None:
    f.write(f"set({var_name}\n")
    for value in values:
        f.write(f'    "{value}"\n')
    f.write(")\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=pathlib.Path)
    parser.add_argument("repo_root", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    if not args.manifest.exists():
        die(f"manifest file missing: {args.manifest}")
    repo_root = args.repo_root.resolve()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))

    public_headers = collect_entries(manifest, "public_headers", repo_root)
    static_libs = collect_entries(manifest, "static_libraries", repo_root)
    shared_libs = collect_entries(manifest, "shared_libraries", repo_root)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as out_file:
        out_file.write(
            "# Generated by scripts/cmake/generate_filter_chain_standalone_manifest_info.py\n"
        )
        write_list(out_file, "GOGGLES_FILTER_STANDALONE_PUBLIC_HEADERS", public_headers)
        write_list(out_file, "GOGGLES_FILTER_STANDALONE_STATIC_LIBRARIES", static_libs)
        write_list(out_file, "GOGGLES_FILTER_STANDALONE_SHARED_LIBRARIES", shared_libs)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
