package:
  name: expected-lite
  version: "0.8.0"

source:
  git: https://github.com/martinmoene/expected-lite.git
  tag: v0.8.0

build:
  number: 0
  script:
    - cmake -B build -G Ninja
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=$PREFIX
      -DEXPECTED_LITE_OPT_BUILD_TESTS=OFF
      -DEXPECTED_LITE_OPT_BUILD_EXAMPLES=OFF
    - cmake --install build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja

about:
  homepage: https://github.com/martinmoene/expected-lite
  license: BSL-1.0
  summary: expected lite - Expected objects in C++11 and later in a single-file header-only library
