package:
  name: sysroot-i686
  version: "2.31"

source:
  url: https://github.com/K1ngst0m/Goggles/releases/download/sysroot-i686-2.31.0/sysroot-i686-2.31.tar.xz
  sha256: d2dfb5277ada92040ae16fa14acf659a48f7e0032dbf17464d727ef27b6adf5f

build:
  number: 1
  script: |
    set -e

    # Install prebuilt sysroot
    # rattler-build auto-enters the tarball's top-level directory (i686-sysroot)
    # so we have usr/, lib, include directly in the work directory
    rm -rf "$PREFIX/i686-sysroot"
    mkdir -p "$PREFIX/i686-sysroot"
    cp -a usr lib include "$PREFIX/i686-sysroot/"

requirements:
  build:
    - tar
    - xz
