package:
  name: vulkansdk
  version: "1.4.328.1"

source:
  url: https://vulkan.lunarg.com/sdk/download/1.4.328.1/linux/vulkansdk-linux-x86_64-1.4.328.1.tar.xz
  sha256: 241e75b56c91c0d210ed07a7c638ec05a3e5b0e4c66ba9f0ba0f102d823ad6bf

build:
  number: 0
  # Skip binary relocation for pre-built binaries provided by LunarG
  dynamic_linking:
    binary_relocation: false
  script:
    - mkdir -p $PREFIX
    - cp -a x86_64/bin $PREFIX/
    - cp -a x86_64/include $PREFIX/
    - cp -a x86_64/lib $PREFIX/
    - cp -a x86_64/share $PREFIX/
    - mkdir -p $PREFIX/share/licenses/vulkansdk
    - cp LICENSE.txt $PREFIX/share/licenses/vulkansdk/
    - mkdir -p $PREFIX/share/vulkan/config
    - cp config/vk_layer_settings.txt $PREFIX/share/vulkan/config/
    - mkdir -p $PREFIX/etc/conda/activate.d $PREFIX/etc/conda/deactivate.d
    - |
      cat <<'EOF' > $PREFIX/etc/conda/activate.d/vulkansdk.sh
      export VULKAN_SDK="$CONDA_PREFIX"
      export VK_LAYER_PATH="$CONDA_PREFIX/share/vulkan/explicit_layer.d"
      EOF
    - |
      cat <<'EOF' > $PREFIX/etc/conda/deactivate.d/vulkansdk.sh
      unset VULKAN_SDK
      unset VK_LAYER_PATH
      EOF

about:
  homepage: https://vulkan.lunarg.com/
  license: LicenseRef-VulkanSDK-Bundle
  summary: Prebuilt Vulkan SDK (LunarG) with loader, validation layers, tools, and headers for Linux x86_64
